#!/bin/sh /etc/rc.common
# Oxidns init script for OpenWrt
# Provides procd-based startup

START=50
STOP=50

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/oxidns -c /etc/oxidns/config.yaml
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	procd_kill
}
